steps:
  push-latest:
    image: plugins/docker
    settings:
      repo: lblod/clbv-form-management-service
      tags: latest
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: push